# Generated by Django 3.0.3 on 2020-05-12 22:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('temphum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, verbose_name='codigo')),
                ('latitud', models.IntegerField(verbose_name='latitud')),
                ('longitud', models.IntegerField(verbose_name='longitud')),
                ('producto', models.CharField(choices=[('Leche', 'Leche'), ('Cacao', 'Cacao'), ('Carnes', 'Carnes'), ('Flores', 'Flores'), ('Hortalizas', 'Hortalizas')], default='Leche', max_length=30)),
                ('validacion', models.PositiveIntegerField(verbose_name='validacion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
